replicaCount: 1

image:
  repository: {{repositoryName}}/{{dashCase name}}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000


livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
