apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-boilerplate
  template:
    metadata:
      labels:
        app: microservice-boilerplate
    spec:
      containers:
        - name: microservice-boilerplate
          image: your-docker-repo/microservice-boilerplate:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: microservice-boilerplate-config
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-boilerplate
spec:
  selector:
    app: microservice-boilerplate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
